In [6]:
import math
import matplotlib.pyplot as plt
from tensorflow import keras
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import *
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from keras.callbacks import EarlyStopping
df=pd.read_csv("/home/sh4n1/miniproj/h1cpudata.csv")
df=df.drop(['Timestamp'],axis=1)
print(df.shape)
df.head(5)

(8634, 1)


cpu_usage
0  10912.027692
1  10890.570362
2  10434.114431
3  10539.450415
4  10951.041020

In [7]:
print(df.iloc[0:, 3:4].values,df['cpu_usage'])


[] 0       10912.027692
1       10890.570362
2       10434.114431
3       10539.450415
4       10951.041020
            ...     
8629       83.878654
8630       81.927988
8631       76.075989
8632       85.829320
8633       83.878654
Name: cpu_usage, Length: 8634, dtype: float64


In [8]:
training_set = df.iloc[:6908, 3:4].values
test_set = df.iloc[6908:, 3:4].values

In [9]:
# Feature Scaling
sc = MinMaxScaler()
training_set_scaled = sc.fit_transform(df)
# Creating a data structure with 1 time-step and 1 output
X_train = []
y_train = []
for i in range(1, 6908):
    X_train.append(training_set_scaled[i-1:i, 0])
    y_train.append(training_set_scaled[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
#(740, 60, 1)

In [10]:
model = Sequential()
#Adding the first LSTM layer and some Dropout regularisation
model.add(LSTM(units = 50, return_sequences = True, input_shape = (X_train.shape[1], 1)))
model.add(Dropout(0.2))
# Adding a second LSTM layer and some Dropout regularisation
model.add(LSTM(units = 50, return_sequences = True))
model.add(Dropout(0.2))
# Adding a third LSTM layer and some Dropout regularisation
model.add(LSTM(units = 50, return_sequences = True))
model.add(Dropout(0.2))
# Adding a fourth LSTM layer and some Dropout regularisation
model.add(LSTM(units = 50))
model.add(Dropout(0.2))
# Adding the output layer
model.add(Dense(units = 1))

# Compiling the RNN
model.compile(optimizer = 'adam', loss = 'mean_squared_error')

# Fitting the RNN to the Training set
model.fit(X_train, y_train, epochs = 100, batch_size = 32)




2021-11-10 18:01:34.229672: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-10 18:01:34.230844: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-11-10 18:01:34.231209: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2021-11-10 18:01:34.231355: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2021-11-10 18:01:34.231500: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

Epoch 1/100
216/216 [==============================] - 9s 13ms/step - loss: 0.0104
Epoch 2/100
216/216 [==============================] - 4s 16ms/step - loss: 0.0029
Epoch 3/100
216/216 [==============================] - 4s 16ms/step - loss: 0.0029
Epoch 4/100
216/216 [==============================] - 4s 16ms/step - loss: 0.0027
Epoch 5/100
216/216 [==============================] - 3s 16ms/step - loss: 0.0028
Epoch 6/100
216/216 [==============================] - 4s 17ms/step - loss: 0.0026
Epoch 7/100
216/216 [==============================] - 4s 17ms/step - loss: 0.0028
Epoch 8/100
216/216 [==============================] - 3s 16ms/step - loss: 0.0027
Epoch 9/100
216/216 [==============================] - 3s 16ms/step - loss: 0.0028
Epoch 10/100
216/216 [==============================] - 3s 16ms/step - loss: 0.0028
Epoch 11/100
216/216 [==============================] - 3s 16ms/step - loss: 0.0028
Epoch 12/100
216/216 [==============================] - 4s 16ms/step - loss: 0.0029
E

216/216 [==============================] - 4s 18ms/step - loss: 0.0025
Epoch 99/100
216/216 [==============================] - 4s 18ms/step - loss: 0.0026
Epoch 100/100
216/216 [==============================] - 4s 17ms/step - loss: 0.0026


In [20]:
X_train.shape

(6907, 1, 1)

In [12]:
dataset_train = df.iloc[:6908]
dataset_test = df.iloc[6908:]
dataset_total = pd.concat((dataset_train, dataset_test), axis = 1,ignore_index = True)
print(dataset_total)

inputs = dataset_total[len(dataset_total) - len(dataset_test) - 1:].values
print(inputs)
inputs.shape

inputs = inputs.reshape(-1,1)
print(inputs)

inputs = sc.transform(inputs)
print(inputs)

                 0          1
0     10912.027692        NaN
1     10890.570362        NaN
2     10434.114431        NaN
3     10539.450415        NaN
4     10951.041020        NaN
...            ...        ...
8629           NaN  83.878654
8630           NaN  81.927988
8631           NaN  76.075989
8632           NaN  85.829320
8633           NaN  83.878654

[8634 rows x 2 columns]
[[79.97732131         nan]
 [        nan 83.87865405]
 [        nan 68.27332307]
 ...
 [        nan 76.07598856]
 [        nan 85.82932043]
 [        nan 83.87865405]]
[[79.97732131]
 [        nan]
 [        nan]
 ...
 [85.82932043]
 [        nan]
 [83.87865405]]
[[0.00188292]
 [       nan]
 [       nan]
 ...
 [0.00239644]
 [       nan]
 [0.00222527]]


/home/sh4n1/.local/lib/python3.9/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


In [19]:
# Getting the predicted stock price of 2017
dataset_train = df.iloc[:6908,0]
dataset_test = df.iloc[6908:,0]
dataset_total = pd.concat((dataset_train, dataset_test), axis = 0,ignore_index = True)
inputs = dataset_total[len(dataset_total) - len(dataset_test) - 1:].values
#inputs = dataset_train.values
inputs = inputs.reshape(-1,1)
inputs = sc.transform(inputs)
print(inputs)
X_test = []
for i in range(6908,8634):
    X_test.append(inputs[i-1:i,0])
X_test = np.array(X_test)
print(X_test)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
print(X_test.shape)
# (459, 60, 1)

[[0.00188292]
 [0.00222527]
 [0.00085587]
 ...
 [0.00154057]
 [0.00239644]
 [0.00222527]]
[]
(1726, 0, 1)


/home/sh4n1/.local/lib/python3.9/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


In [17]:
#import torch
predicted_cpu_usage= model.predict(X_test)
predicted_cpu_usage = sc.inverse_transform(predicted_cpu_usage)

ValueError: in user code:

    /home/sh4n1/.local/lib/python3.9/site-packages/keras/engine/training.py:1586 predict_function  *
        return step_function(self, iterator)
    /home/sh4n1/.local/lib/python3.9/site-packages/keras/engine/training.py:1576 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /home/sh4n1/.local/lib/python3.9/site-packages/tensorflow/python/distribute/distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/sh4n1/.local/lib/python3.9/site-packages/tensorflow/python/distribute/distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/sh4n1/.local/lib/python3.9/site-packages/tensorflow/python/distribute/distribute_lib.py:3632 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/sh4n1/.local/lib/python3.9/site-packages/keras/engine/training.py:1569 run_step  **
        outputs = model.predict_step(data)
    /home/sh4n1/.local/lib/python3.9/site-packages/keras/engine/training.py:1537 predict_step
        return self(x, training=False)
    /home/sh4n1/.local/lib/python3.9/site-packages/keras/engine/base_layer.py:1037 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    /home/sh4n1/.local/lib/python3.9/site-packages/keras/engine/sequential.py:369 call
        return super(Sequential, self).call(inputs, training=training, mask=mask)
    /home/sh4n1/.local/lib/python3.9/site-packages/keras/engine/functional.py:414 call
        return self._run_internal_graph(
    /home/sh4n1/.local/lib/python3.9/site-packages/keras/engine/functional.py:550 _run_internal_graph
        outputs = node.layer(*args, **kwargs)
    /home/sh4n1/.local/lib/python3.9/site-packages/keras/layers/recurrent.py:659 __call__
        return super(RNN, self).__call__(inputs, **kwargs)
    /home/sh4n1/.local/lib/python3.9/site-packages/keras/engine/base_layer.py:1037 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    /home/sh4n1/.local/lib/python3.9/site-packages/keras/layers/recurrent_v2.py:1253 call
        runtime) = lstm_with_backend_selection(**normal_lstm_kwargs)
    /home/sh4n1/.local/lib/python3.9/site-packages/keras/layers/recurrent_v2.py:1648 lstm_with_backend_selection
        last_output, outputs, new_h, new_c, runtime = defun_standard_lstm(**params)
    /home/sh4n1/.local/lib/python3.9/site-packages/tensorflow/python/eager/function.py:3038 __call__
        filtered_flat_args) = self._maybe_define_function(args, kwargs)
    /home/sh4n1/.local/lib/python3.9/site-packages/tensorflow/python/eager/function.py:3463 _maybe_define_function
        graph_function = self._create_graph_function(args, kwargs)
    /home/sh4n1/.local/lib/python3.9/site-packages/tensorflow/python/eager/function.py:3298 _create_graph_function
        func_graph_module.func_graph_from_py_func(
    /home/sh4n1/.local/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py:1007 func_graph_from_py_func
        func_outputs = python_func(*func_args, **func_kwargs)
    /home/sh4n1/.local/lib/python3.9/site-packages/keras/layers/recurrent_v2.py:1379 standard_lstm
        last_output, outputs, new_states = backend.rnn(
    /home/sh4n1/.local/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py:206 wrapper
        return target(*args, **kwargs)
    /home/sh4n1/.local/lib/python3.9/site-packages/keras/backend.py:4351 rnn
        [inp[0] for inp in flatted_inputs])
    /home/sh4n1/.local/lib/python3.9/site-packages/keras/backend.py:4351 <listcomp>
        [inp[0] for inp in flatted_inputs])
    /home/sh4n1/.local/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py:206 wrapper
        return target(*args, **kwargs)
    /home/sh4n1/.local/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py:1041 _slice_helper
        return strided_slice(
    /home/sh4n1/.local/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py:206 wrapper
        return target(*args, **kwargs)
    /home/sh4n1/.local/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py:1214 strided_slice
        op = gen_array_ops.strided_slice(
    /home/sh4n1/.local/lib/python3.9/site-packages/tensorflow/python/ops/gen_array_ops.py:10538 strided_slice
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    /home/sh4n1/.local/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py:748 _apply_op_helper
        op = g._create_op_internal(op_type_name, inputs, dtypes=None,
    /home/sh4n1/.local/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py:599 _create_op_internal
        return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
    /home/sh4n1/.local/lib/python3.9/site-packages/tensorflow/python/framework/ops.py:3561 _create_op_internal
        ret = Operation(
    /home/sh4n1/.local/lib/python3.9/site-packages/tensorflow/python/framework/ops.py:2041 __init__
        self._c_op = _create_c_op(self._graph, node_def, inputs,
    /home/sh4n1/.local/lib/python3.9/site-packages/tensorflow/python/framework/ops.py:1883 _create_c_op
        raise ValueError(str(e))

    ValueError: slice index 0 of dimension 0 out of bounds. for '{{node strided_slice_1}} = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1](transpose, strided_slice_1/stack, strided_slice_1/stack_1, strided_slice_1/stack_2)' with input shapes: [0,?,1], [1], [1], [1] and with computed input tensors: input[1] = <0>, input[2] = <1>, input[3] = <1>.
